---
version: "2"
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "errcheck"
    - "errname"
    - "errorlint"
    - "goprintffuncname"
    - "gosec"
    - "govet"
    - "importas"
    - "ineffassign"
    - "makezero"
    - "prealloc"
    - "predeclared"
    - "promlinter"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "unconvert"
    - "unused"
    - "usetesting"
    - "wastedassign"
    - "whitespace"
  settings:
    staticcheck:
      dot-import-whitelist:
        - "github.com/onsi/ginkgo/v2"
        - "github.com/onsi/gomega"
  exclusions:
    generated: "lax"
    presets:
      - "comments"
      - "common-false-positives"
      - "legacy"
      - "std-error-handling"
    paths:
      - "third_party$"
      - "builtin$"
      - "examples$"
formatters:
  enable:
    - "gofumpt"
    - "goimports"
  settings:
    goimports:
      local-prefixes:
        - "github.com/authzed/spicedb-operator"
  exclusions:
    generated: "lax"
    paths:
      - "third_party$"
      - "builtin$"
      - "examples$"
