apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds
  - rbac
  - operator.yaml
images:
  - name: ghcr.io/authzed/spicedb-operator
    newTag: latest
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: update-graph
    namespace: spicedb-operator
    files:
      - update-graph.yaml
